apiVersion: v1
kind: Service
metadata:
  name: nikestore-service
spec:
  selector:
    app: nikestore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer  # Change to NodePort if running on a bare-metal cluster
